name: Build and Publish Docker images

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  ERLANG_MAJOR: "25"
  ERLANG: "25.1"
  OS_VERSION: "3.16.2"
  ELIXIR: "1.14.0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            ELIXIR=${{ env.ELIXIR }}
            ERLANG_MAJOR=${{ env.ERLANG_MAJOR }}
            OS_VERSION=${{ env.OS_VERSION }}
            ERLANG=${{ env.ERLANG }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/elixir:${{ env.ELIXIR }}-otp-${{ env.ERLANG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
