name: Build and Publish Docker images

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  ERLANG_MAJOR: "26"
  ERLANG: "26.1.1"
  OS_VERSION: "3.18.4"
  ELIXIR: "1.15.6"

jobs:
  build:
    # This is a dedicated, beefy runner so that we can quickly build cross-platform
    # images in case we need to quickly push a fix to prod in the case of a CVE
    # or bug.
    runs-on: ubuntu-22.04-buildx
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            ELIXIR=${{ env.ELIXIR }}
            ERLANG_MAJOR=${{ env.ERLANG_MAJOR }}
            OS_VERSION=${{ env.OS_VERSION }}
            ERLANG=${{ env.ERLANG }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/elixir:${{ env.ELIXIR }}-otp-${{ env.ERLANG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
