name: Build and Publish Docker images

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  ERLANG_MAJOR: "26"
  ERLANG: "26.1.1"
  OS_VERSION: "3.18.4"
  ELIXIR: "1.15.6"

jobs:
  build:
    strategy:
      matrix:
        include:
          - runner: ubuntu-22.04-firezone
            platforms: linux/amd64,linux/arm64
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Build and push
        uses: docker/build-push-action@v3
        id: build
        with:
          push: true
          file: Dockerfile
          platforms: ${{ matrix.platforms }}
          build-args: |
            ELIXIR=${{ env.ELIXIR }}
            ERLANG_MAJOR=${{ env.ERLANG_MAJOR }}
            OS_VERSION=${{ env.OS_VERSION }}
            ERLANG=${{ env.ERLANG }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/elixir/:${{ env.ELIXIR }}-otp-${{ env.ERLANG }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/elixir:${{ env.ELIXIR }}-otp-${{ env.ERLANG }}
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/elixir:${{ env.ELIXIR }}-otp-${{ env.ERLANG }}
